[package]
name = "lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "^1.0.2"
lambda_http = "^1.0.2"
serde = "^1.0.228"
serde_json = "^1.0.149"

tokio = { version = "^1", features = ["macros"] }
