[package]
name = "lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "^1.0.0"
lambda_http = "^1.0.0"
serde = "^1"
serde_json = "^1"

tokio = { version = "^1", features = ["macros"] }
